# Generated by Django 5.2.13 on 2026-04-26 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('genre', models.CharField(choices=[('fic', 'Fiction'), ('sci', 'Science Fiction'), ('fan', 'Fantasy'), ('adv', 'Action Adventure'), ('his', 'Historical Fiction'), ('rom', 'Romance')], max_length=20, null=True)),
                ('author', models.CharField(max_length=250)),
                ('sbn_code', models.CharField(max_length=50)),
                ('book_id', models.BigAutoField(db_column='book_id', primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'bookstore_book',
                'abstract': False,
            },
        ),
    ]
